# 开发环境配置
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zx_ai_learning
    password: root
  data:
    redis:
      host: 192.168.12.168

minio:
  endpoint: http://192.168.12.168:9000
  access-key: adminadmin
  secret-key: adminadmin

# 前端地址配置
frontend:
  url: http://localhost:5173

# 支付宝沙箱配置
alipay:
  notify-url: http://localhost:8080/web/alipay/notify
  return-url: http://localhost:8080/web/alipay/return

rocketmq:
  name-server: 192.168.12.168:9876

