# 生产环境配置
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://81.71.143.129:3306/zx_ai_learning
    password: Zxai@2025#
  data:
    redis:
      host: 81.71.143.129

minio:
  accessKey: admin
  secretKey: admin123456
  endpoint: http://81.71.143.129:9000

# 前端地址配置
frontend:
  url: http://81.71.143.129

# 支付宝沙箱配置
alipay:
  notify-url: http://81.71.143.129:8080/web/alipay/notify
  return-url: http://81.71.143.129:8080/web/alipay/return

rocketmq:
  name-server: 81.71.143.129:9876

